# https://github.com/dgraph-io/dgraph/raw/master/contrib/config/docker/docker-compose.yml
# This Docker Compose file can be used to quickly bootup Dgraph Zero
# and Alpha in different Docker containers.

# It mounts /tmp/data on the host machine to /dgraph within the
# container. You can change /tmp/data to a more appropriate location.
# Run `docker-compose up` to start Dgraph.

version: "3.2"
services:
  zero:
    image: dgraph/dgraph:v20.11.2
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
    networks:
      - local-dgraph
  alpha:
    image: dgraph/dgraph:v20.11.2
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --whitelist 0.0.0.0/0
    networks:
      - local-dgraph
  ratel:
    image: dgraph/dgraph:v20.11.2
    ports:
      - 8000:8000
    command: dgraph-ratel
    networks:
      - local-dgraph
networks:
  local-dgraph:
